[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tcdiag_realtime.py"
authors = [{name = "Jonathan Vigh", email = "jvigh@ucar.edu"}]
dynamic = ["version", "description"]